services:
  db:
    image: docker.io/postgis/postgis:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    image: docker.io/library/node:latest
    working_dir: /app
    volumes:
      - ../api:/app
    command: sh -c "npm install && npm run easyStart"
    environment:
      NODE_ENV: production
      PRISMA_DATABASE_URL: ${PRISMA_DATABASE_URL}
      JWT_SECRET: ${API_JWT_SECRET}
      JWT_EXPIRATION: ${API_JWT_EXPIRATION}
      PORT: ${API_PORT}
    depends_on:
      - db

  nginx:
    image: docker.io/library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web_admin/web_admin/browser:/usr/share/nginx/html:ro
    depends_on:
      - db

networks:
  default:
    driver: bridge