name: Build Flutter App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'
      - run: flutter pub get
        working-directory: services/client
      - name: Generate API Protos
        run: |
        sudo apt-get update && sudo apt-get install -y protobuf-compiler
        mkdir -p services/client/lib/data/proto
        pub global activate protoc_plugin
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        protoc -I=proto --dart_out=grpc:services/client/lib/data/proto proto/api/v1/*.proto proto/common/*.proto
      - run: flutter build apk --release
        working-directory: services/client
      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: services/client/build/app/outputs/flutter-apk/app-release.apk
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: services/client/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}